[package]
name = "sui-contracts"
version = "0.0.1"
license = "MIT"

[dependencies]
Sui = { local = "../sui/crates/sui-framework/packages/sui-framework" }
#Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
[addresses]
ibt = "0x0"

[build]

